//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentminiportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni
    {
        public string jobstatus { get; set; }
        public Nullable<System.DateTime> complition_date { get; set; }
        public string regno { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
