//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentminiportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_
    {
        public int alumni_id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public string address { get; set; }
        public string department { get; set; }
        public string section { get; set; }
        public Nullable<int> graduation_year { get; set; }
        public string arid_number { get; set; }
        public string technology { get; set; }
        public string gender { get; set; }
    }
}
