//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentminiportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedSurvey
    {
        public int AssignmentID { get; set; }
        public string Section { get; set; }
        public Nullable<int> Semester { get; set; }
        public string Department { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public string Technology { get; set; }
        public Nullable<int> GraduationYear { get; set; }
        public string studentType { get; set; }
    
        public virtual createsurvey createsurvey { get; set; }
    }
}
