//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentminiportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class posts
    {
        public int p_id { get; set; }
        public Nullable<System.DateTime> p_date { get; set; }
        public Nullable<System.TimeSpan> p_time { get; set; }
        public byte[] p_image { get; set; }
        public Nullable<int> e_id { get; set; }
    }
}
