//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentminiportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class surveyCurrentStudent
    {
        public int id { get; set; }
        public Nullable<int> surveryId { get; set; }
        public string gender { get; set; }
        public string degree { get; set; }
        public string semester { get; set; }
        public string section { get; set; }
    }
}
