//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentminiportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class surveyAllumini
    {
        public int id { get; set; }
        public Nullable<int> suveryId { get; set; }
        public Nullable<int> year { get; set; }
        public string degree { get; set; }
        public string location { get; set; }
        public string technology { get; set; }
        public string gender { get; set; }
    }
}
