//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentminiportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResponse
    {
        public int SurveyResponseID { get; set; }
        public int SurveyID { get; set; }
        public int SurveyQuestionID { get; set; }
        public int SelectedOptionID { get; set; }
    
        public virtual bothstudent bothstudent { get; set; }
    }
}
